### ISSUE TITLE
Здравствуйте! Вы не знаете, как заставить API Яндекс переводчика отправлять тебе все возможные переводы слова, а не только один перевод?

### ISSUE THREAD

**Issue by dimalosev0605** [Artemyev-Sergei/Qt-YandexTranslate#5]

**Comment by Artemyev-Sergei** [comment]
@dimalosev0605, здравствуйте! 

Насколько мне известно, с помощью API [Yandex.Translate](https://tech.yandex.com/translate/doc/dg/concepts/About-docpage/) нет возможности удобным способом реализовать подобный функционал. Однако среди методов API [Yandex.Dictionary](https://tech.yandex.com/dictionary/doc/dg/concepts/About-docpage/) есть все необходимое для того, чтобы выполнить описанное вами функциональное требование. В данном проекте API [Yandex.Dictionary](https://tech.yandex.com/dictionary/doc/dg/concepts/About-docpage/) используется для получения всех доступных словарных записей по отдельному слову, среди которых есть различные варианты его перевода.

Словарные записи в данном проекте выводятся в консоль. К сожалению, у меня сейчас нет возможности собрать этот проект, чтобы записать на видео и наглядно показать сам процесс, но если у вас есть возможность запустить проект в Debug-режиме из редактора Qt, то в главном окне вы сможете найти кнопку "Search in the dictionary". Если в качестве текста для перевода было указано одно слово, то после нажатия на данную кнопку в консоли Qt вы сможете увидеть все возможные записи, полученные из [Yandex.Dictionary](https://tech.yandex.com/dictionary/doc/dg/concepts/About-docpage/) и доступные для данного слова (его возможные переводы, примеры использования и т.п.). Подробности реализации можно посмотреть здесь: [on_dictionaryButton_clicked](https://github.com/Artemyev-Sergei/Qt-YandexTranslate/blob/master/mainwindow.cpp), [getDictionaryEntry](https://github.com/Artemyev-Sergei/Qt-YandexTranslate/blob/master/dictionary_api.cpp) и [showEntry](https://github.com/Artemyev-Sergei/Qt-YandexTranslate/blob/master/dictionary_api.cpp).

Надеюсь, я смог вам помочь! Сообщите, пожалуйста, если у вас остались какие-либо вопросы!
